const ScreenConst = {
  SPLASH_SCREEN: 'SplashScreen',
  MAIN_TAB_BOTTOM_SCREEN: 'MainTabBottomScreen',
  HOME_SCREEN: 'HomeScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  SERVICE_SCREEN: 'ServiceScreen',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  CHOOSE_ROLE_SCREEN: 'CHOOSE_ROLE_SCREEN',
  SCAN_QR_SCREEN: 'SCAN_QR_SCREEN',
  QR_CODE_SCREEN: 'QR_CODE_SCREEN',
  QR_CODE_ATTENTION_SCREEN: 'QR_CODE_ATTENTION_SCREEN',
  ADD_USER_SCREEN: 'ADD_USER_SCREEN',
};

export { ScreenConst };
