const ScreenConst = {
  SPLASH_SCREEN: 'SplashScreen',
  MAIN_TAB_BOTTOM_SCREEN: 'MainTabBottomScreen',
  HOME_SCREEN: 'HomeScreen',
  HOME_USER_SCREEN: 'HomeUserScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  SERVICE_SCREEN: 'ServiceScreen',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  CHOOSE_ROLE_SCREEN: 'CHOOSE_ROLE_SCREEN',
  SCAN_QR_SCREEN: 'SCAN_QR_SCREEN',
  QR_CODE_SCREEN: 'QR_CODE_SCREEN',
  QR_CODE_ATTENTION_SCREEN: 'QR_CODE_ATTENTION_SCREEN',
  ADD_USER_SCREEN: 'ADD_USER_SCREEN',
  ADDITIONAL_WORK_SCREEN: 'ADDITIONAL_WORK_SCREEN',
  ADDITIONAL_WORK_LIST_SCREEN: 'ADDITIONAL_WORK_LIST_SCREEN',
  ADDITIONAL_SCAN_QR_SCREEN: 'ADDITIONAL_SCAN_QR_SCREEN',
  ADD_COMPANY_SCREEN: 'ADD_COMPANY_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  SALARY_SCREEN: 'SALARY_SCREEN',
};

export { ScreenConst };
