const ScreenConst = {
  SPLASH_SCREEN: 'SplashScreen',
  MAIN_TAB_BOTTOM_SCREEN: 'MainTabBottomScreen',
  HOME_SCREEN: 'HomeScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  POST_SCREEN: 'PostScreen',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  CHOOSE_ROLE_SCREEN: 'CHOOSE_ROLE_SCREEN',
  SCAN_QR_SCREEN: 'SCAN_QR_SCREEN',
  QR_CODE_SCREEN: 'QR_CODE_SCREEN',
};

export { ScreenConst };
